---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: generativeaiservice
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
    - '*'
    methods:
    - '*'
    port: 0
    rewrite: /generativeaisrvc/get_policy_mapped
    type: prefix
    url: /generativeaisrvc/get_policy_mapped
  targets:
  - host: generativeaiservice.unotech.svc.cluster.local
    port: 8080
    scheme: http
    type: ""
    version: ""
    weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: generativeaiservice
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
    - '*'
    methods:
    - '*'
    port: 0
    rewrite: /generativeaisrvc/map_fields_to_policy
    type: prefix
    url: /generativeaisrvc/map_fields_to_policy
  targets:
  - host: generativeaiservice.unotech.svc.cluster.local
    port: 8080
    scheme: http
    type: ""
    version: ""
    weight: 100
type: ingress-route
---